# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d146f6490df9b9ebbe9beb5ce01c02c532ba5c6047aa02f1521dcde2c2e723a3d00500ad13c7e535c332b12d7f44745bd7a1f90e67b13e02b5954ddbc873956c

test:
  secret_key_base: 44c0492e21e04ba5a3ef887351e12e4a18135662b50ad1aacb957cbce594f2dad7925a851f3bde39f254ada060b3789daa0ec7a0715f11d149ee257c10e5d0df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
